// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// templ Privacy() {
//     @Base("Privacy Policy"){
//          <section class="policy-section">
//         <h1>Privacy Policy for Goldco-op</h1>
//         <p class="mb-2"><strong>Effective Date:</strong> September 2025</p>
//         <p>Goldco-op (“we,” “our,” “us”) is operated by Gold Savings &amp; Investment Cooperative Society. We are committed to protecting your privacy and ensuring that your personal information is handled in a safe and responsible way. This Privacy Policy explains how we collect, use, disclose, and protect your information when you use our website, mobile app, and services.</p>

//          <h2>1. Information We Collect</h2>
//         <ul>
//             <li><strong>Personal Information:</strong> Name, phone number, email address, date of birth, and bank details (for deposits, withdrawals, and transfers).</li>
//             <li><strong>Transaction Information:</strong> Deposits, savings history, token rewards, and redemption activity.</li>
//             <li><strong>Device Information:</strong> Device type, operating system, unique device identifiers, and IP address.</li>
//             <li><strong>Usage Data:</strong> App interactions, preferences, and activities to improve user experience.</li>
//         </ul>

//         <h2>2. How We Use Your Information</h2>
//         <ul>
//             <li>Provide and manage your savings &amp; investment wallet with the cooperative Society.</li>
//             <li>Track deposits and reward tokens.</li>
//             <li>Allow token conversion to airtime or cash (coming soon).</li>
//             <li>Send you transaction alerts, updates, and promotional offers.</li>
//             <li>Improve our services, security, and app performance.</li>
//             <li>Comply with legal and regulatory requirements.</li>
//         </ul>

//         <h2>3. Sharing of Information</h2>
//         <ul>
//             <li>We do not sell or rent your personal information. We may share data only in the following situations:</li>
//             <li><strong>Service Providers:</strong> With trusted third parties who help us process payments, airtime conversions, and app hosting.</li>
//             <li><strong>Legal Compliance:</strong> When required by law, regulation, or government request.</li>
//             <li><strong>Business Transfers:</strong> In case of a merger, acquisition, or restructuring, your data may be transferred to the new entity.</li>
//         </ul>

//         <h2>4. Security of Your Data</h2>
//         <p>We take reasonable steps to protect your information, including encryption, secure servers, and restricted access. However, no method of transmission or storage is 100% secure. We encourage you to safeguard your login details.</p>

//         <h2>5. Your Rights</h2>
//         <ul>
//             <li>Access and request a copy of your personal data.</li>
//             <li>Correct inaccurate or incomplete data.</li>
//             <li>Request deletion of your data (subject to legal obligations).</li>
//             <li>Opt out of marketing communications at any time.</li>
//         </ul>

//         <h2>6. Cookies &amp; Tracking</h2>
//         <p>Our website and app may use cookies and similar technologies to improve user experience, track performance, and personalize services. You can manage cookies in your browser settings.</p>

//         <h2>7. Third-Party Links</h2>
//         <p>Goldco-op may contain links to third-party sites (e.g., payment gateways). We are not responsible for the privacy practices of those sites.</p>

//         <h2>8. Children’s Privacy</h2>
//         <p>Goldco-op is not intended for individuals under the age of 18. We do not knowingly collect data from children.</p>

//         <h2>9. Updates to This Policy</h2>
//         <p>We may update this Privacy Policy from time to time. Changes will be posted on this page with a revised effective date.</p>

//	        <h2>10. Contact Us</h2>
//	        <div class="contact-info">
//	            <p><i class="fas fa-envelope"></i> Email: <a href="mailto:support@goldco-op.com.ng" style="color:#2fb6b6;">support@goldco-op.com.ng</a></p>
//	            <p><i class="fas fa-globe"></i> Website: <a href="https://www.goldco-op.com.ng" style="color:#2fb6b6;">www.goldco-op.com.ng</a></p>
//	        </div>
//	    </section>
//	    }
//	}
func Privacy() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<h1>Privacy</h1>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
