services:
  postgres:
    container_name: goldsavings_postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT}:${DB_PORT}'

  redis:
    container_name: goldsavings_redis
    image: redis:alpine
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    command: redis-server --appendonly yes
    volumes:
      - ./redis_data:/data
    restart: unless-stopped