// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Admin struct {
	ID           int32        `json:"id"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

type Investment struct {
	ID           int32        `json:"id"`
	UserID       int32        `json:"user_id"`
	PlanID       int32        `json:"plan_id"`
	ReferenceID  string       `json:"reference_id"`
	Amount       int32        `json:"amount"`
	Interest     string       `json:"interest"`
	InterestRate string       `json:"interest_rate"`
	Status       string       `json:"status"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
}

type InvestmentPlan struct {
	ID           int32        `json:"id"`
	Name         string       `json:"name"`
	InterestRate string       `json:"interest_rate"`
	Description  string       `json:"description"`
	MinAmount    string       `json:"min_amount"`
	MaxAmount    string       `json:"max_amount"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

type PayoutRequest struct {
	ID            int32          `json:"id"`
	UserID        int32          `json:"user_id"`
	AccountName   sql.NullString `json:"account_name"`
	PhoneNumber   sql.NullString `json:"phone_number"`
	BankName      sql.NullString `json:"bank_name"`
	AccountNumber sql.NullString `json:"account_number"`
	InvestmentID  sql.NullInt32  `json:"investment_id"`
	Type          string         `json:"type"`
	Category      string         `json:"category"`
	Amount        string         `json:"amount"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type Referral struct {
	ID        int32        `json:"id"`
	InviterID int32        `json:"inviter_id"`
	InviteeID int32        `json:"invitee_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Saving struct {
	ID        int32        `json:"id"`
	UserID    int32        `json:"user_id"`
	Amount    string       `json:"amount"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Transaction struct {
	ID           int32          `json:"id"`
	UserID       int32          `json:"user_id"`
	Amount       int32          `json:"amount"`
	InvestmentID sql.NullInt32  `json:"investment_id"`
	Category     string         `json:"category"`
	Status       string         `json:"status"`
	Type         string         `json:"type"`
	Reason       sql.NullString `json:"reason"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type User struct {
	ID                       int32          `json:"id"`
	Username                 string         `json:"username"`
	Email                    string         `json:"email"`
	Phone                    string         `json:"phone"`
	TotalSavings             int32          `json:"total_savings"`
	TotalSavingsWithdrawn    int32          `json:"total_savings_withdrawn"`
	TotalInvestmentAmount    int32          `json:"total_investment_amount"`
	TotalInvestmentWithdrawn int32          `json:"total_investment_withdrawn"`
	TotalTokens              int32          `json:"total_tokens"`
	ReferenceID              string         `json:"reference_id"`
	PasswordHash             string         `json:"password_hash"`
	AccountNumber            sql.NullString `json:"account_number"`
	BankName                 sql.NullString `json:"bank_name"`
	IsActive                 sql.NullBool   `json:"is_active"`
	EmailVerified            bool           `json:"email_verified"`
	VerificationCode         sql.NullString `json:"verification_code"`
	VerificationExpiresAt    sql.NullTime   `json:"verification_expires_at"`
	CreatedAt                sql.NullTime   `json:"created_at"`
	UpdatedAt                sql.NullTime   `json:"updated_at"`
}
