// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type SavingsPlan struct {
	ID               uuid.UUID    `json:"id"`
	UserID           uuid.UUID    `json:"user_id"`
	PlanRef          string       `json:"plan_ref"`
	TargetAmount     string       `json:"target_amount"`
	CurrentAmount    string       `json:"current_amount"`
	DurationDays     int32        `json:"duration_days"`
	SavingsFrequency string       `json:"savings_frequency"`
	SavingsAmount    string       `json:"savings_amount"`
	Status           string       `json:"status"`
	CreatedAt        sql.NullTime `json:"created_at"`
	UpdatedAt        sql.NullTime `json:"updated_at"`
	MaturityDate     sql.NullTime `json:"maturity_date"`
}

type User struct {
	ID            uuid.UUID      `json:"id"`
	FirstName     string         `json:"first_name"`
	LastName      string         `json:"last_name"`
	Email         string         `json:"email"`
	Phone         string         `json:"phone"`
	PasswordHash  string         `json:"password_hash"`
	AccountNumber sql.NullString `json:"account_number"`
	BankName      sql.NullString `json:"bank_name"`
	TokenBalance  sql.NullInt32  `json:"token_balance"`
	IsActive      sql.NullBool   `json:"is_active"`
	IsAdmin       sql.NullBool   `json:"is_admin"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}
