// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Admin struct {
	ID           uuid.UUID    `json:"id"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

type Investment struct {
	ID           uuid.UUID    `json:"id"`
	UserID       uuid.UUID    `json:"user_id"`
	PlanID       int32        `json:"plan_id"`
	ReferenceID  string       `json:"reference_id"`
	Amount       int32        `json:"amount"`
	Interest     string       `json:"interest"`
	InterestRate string       `json:"interest_rate"`
	Status       string       `json:"status"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
}

type InvestmentPlan struct {
	ID           int32        `json:"id"`
	Name         string       `json:"name"`
	InterestRate string       `json:"interest_rate"`
	MinAmount    string       `json:"min_amount"`
	MaxAmount    string       `json:"max_amount"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

type PayoutRequest struct {
	ID           int32         `json:"id"`
	UserID       uuid.UUID     `json:"user_id"`
	AccountName  string        `json:"account_name"`
	BankName     string        `json:"bank_name"`
	InvestmentID uuid.NullUUID `json:"investment_id"`
	Type         string        `json:"type"`
	Category     string        `json:"category"`
	Amount       string        `json:"amount"`
	CreatedAt    sql.NullTime  `json:"created_at"`
	UpdatedAt    sql.NullTime  `json:"updated_at"`
}

type Saving struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Amount    string       `json:"amount"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Transaction struct {
	ID           int32          `json:"id"`
	UserID       uuid.UUID      `json:"user_id"`
	Amount       int32          `json:"amount"`
	InvestmentID uuid.NullUUID  `json:"investment_id"`
	Type         string         `json:"type"`
	Status       string         `json:"status"`
	Reason       sql.NullString `json:"reason"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type User struct {
	ID                       uuid.UUID      `json:"id"`
	Username                 string         `json:"username"`
	Email                    string         `json:"email"`
	Phone                    string         `json:"phone"`
	TotalSavings             int32          `json:"total_savings"`
	TotalSavingsWithdrawn    int32          `json:"total_savings_withdrawn"`
	TotalInvestmentAmount    int32          `json:"total_investment_amount"`
	TotalInvestmentWithdrawn int32          `json:"total_investment_withdrawn"`
	TotalTokens              int32          `json:"total_tokens"`
	ReferenceID              string         `json:"reference_id"`
	PasswordHash             string         `json:"password_hash"`
	AccountNumber            sql.NullString `json:"account_number"`
	BankName                 sql.NullString `json:"bank_name"`
	TokenBalance             sql.NullInt32  `json:"token_balance"`
	IsActive                 sql.NullBool   `json:"is_active"`
	EmailVerified            bool           `json:"email_verified"`
	VerificationCode         sql.NullString `json:"verification_code"`
	VerificationExpiresAt    sql.NullTime   `json:"verification_expires_at"`
	CreatedAt                sql.NullTime   `json:"created_at"`
	UpdatedAt                sql.NullTime   `json:"updated_at"`
}
